# Generated by Django 4.2.7 on 2024-11-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=50)),
                ("relationship", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("manufacturer", models.CharField(max_length=100)),
                ("device_name", models.CharField(max_length=100)),
                ("expiration_date", models.DateTimeField()),
                ("batch_no", models.CharField(max_length=100)),
                ("sample_type", models.CharField(max_length=50)),
                ("temp_range", models.CharField(max_length=100)),
                ("is_hazardous", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="IoTDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("manufacturer", models.CharField(max_length=100)),
                ("battery_life", models.CharField(max_length=50)),
                ("cycle_count", models.IntegerField(default=0)),
                ("exists", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kit_id", models.CharField(max_length=100, unique=True)),
                ("kit_name", models.CharField(max_length=100)),
                ("return_box_dimensions", models.CharField(max_length=50)),
                (
                    "return_box_weight",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_template", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.device"
                    ),
                ),
                (
                    "iot_device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.iotdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dimensions", models.CharField(max_length=50)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_pieces", models.IntegerField()),
                ("contents", models.JSONField()),
                ("additional_items", models.JSONField(null=True)),
                ("is_template", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("scheduled_collection_dates", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("carrier", models.CharField(max_length=50)),
                ("service_type", models.CharField(max_length=50)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pickup_date", models.DateTimeField(null=True)),
                ("expected_delivery", models.DateTimeField(null=True)),
                ("actual_delivery", models.DateTimeField(null=True)),
                ("requires_signature", models.BooleanField(default=False)),
                ("hold_at_location", models.BooleanField(default=False)),
                ("sample_ids", models.JSONField(null=True)),
                ("notification_emails", models.JSONField(null=True)),
                ("failures", models.JSONField(null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments_to",
                        to="api.address",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments_from",
                        to="api.address",
                    ),
                ),
                ("parcels", models.ManyToManyField(to="api.parcel")),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("kit_inventory", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trial_id", models.CharField(max_length=100, unique=True)),
                ("diagnostic_kits_template", models.JSONField()),
                ("associated_patients", models.ManyToManyField(to="api.patient")),
                (
                    "associated_sites",
                    models.ManyToManyField(related_name="site_trials", to="api.site"),
                ),
                (
                    "default_receive_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trial_receive_address",
                        to="api.address",
                    ),
                ),
                (
                    "default_send_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trial_send_address",
                        to="api.address",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="journey",
            name="user",
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
        migrations.DeleteModel(
            name="Journey",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="site",
            name="associated_trials",
            field=models.ManyToManyField(related_name="trial_sites", to="api.trial"),
        ),
        migrations.AddField(
            model_name="site",
            name="contact_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.contactperson",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="trial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.trial"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="associated_sites",
            field=models.ManyToManyField(related_name="site_patients", to="api.site"),
        ),
        migrations.AddField(
            model_name="patient",
            name="associated_trials",
            field=models.ManyToManyField(to="api.trial"),
        ),
        migrations.AddField(
            model_name="patient",
            name="contact_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.contactperson",
            ),
        ),
    ]
